name: Build And Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Clonar el código del repositorio
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Iniciar sesión en Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # 3️⃣ Construir la imagen de Docker
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-api:${{ github.sha }} .

    # 4️⃣ Subir la imagen a Docker Hub
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-api:${{ github.sha }}
      
  deploy-on-server:
    runs-on: ubuntu-latest

    steps:
    # 5️⃣ Desplegar en el servidor
    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p "${{ secrets.DOCKERHUB_PASSWORD }}"
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend-api:${{ github.sha }}
          sudo docker stop backend-api || true
          sudo docker rm backend-api || true
          sudo docker run -d --name backend-api -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/backend-api:${{ github.sha }}
